/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#131b2e',
        'on-primary-container': '#7c839b',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        'inverse-primary': '#bec6e0',

        secondary: '#006591',
        'on-secondary': '#ffffff',
        'secondary-container': '#39b8fd',
        'on-secondary-container': '#004666',
        'secondary-fixed': '#c9e6ff',
        'secondary-fixed-dim': '#89ceff',
        'on-secondary-fixed': '#001e2f',
        'on-secondary-fixed-variant': '#004c6e',

        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#2a1700',
        'on-tertiary-container': '#b87500',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        surface: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#565e74',

        'on-surface': '#191c1e',
        'on-surface-variant': '#45464d',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',

        outline: '#76777d',
        'outline-variant': '#c6c6cd',

        background: '#f7f9fb',
        'on-background': '#191c1e',

        // Brand accent, referenced as "Insight Orange" in DESIGN.md
        'insight-orange': '#E67E22',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '48px',
        'section-v-padding': '120px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'display-lg': ['"Source Serif 4"', 'serif'],
        'headline-lg': ['"Source Serif 4"', 'serif'],
        'headline-lg-mobile': ['"Source Serif 4"', 'serif'],
        'headline-md': ['"Source Serif 4"', 'serif'],
        'body-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'label-caps': ['"Hanken Grotesk"', 'sans-serif'],
        button: ['"Hanken Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        button: ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
